version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    groups:
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: react
        update-types:
          - version-update:semver-major
      - dependency-name: react-dom
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/react"
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/react-dom"
        update-types:
          - version-update:semver-major

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: monthly

  - package-ecosystem: cargo
    directory: /frontend/src-tauri
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
